### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [HookedBehemoth/neuters#10]
Any plans for docker?

**Comment by HookedBehemoth** [comment]
Not a big fan of docker/podman but maybe I don't understand it.

What's the use in encapsulating this? It pulls in no dependencies and on my server I just have it running as an unprivileged user.

**Comment by EsmailELBoBDev2** [comment]
because for me I self host more than one application 
so docker makes it little easy for me

**Comment by ZekXtreme** [comment]
Would agree with @EsmailELBoBDev2  It Helps when you are hosting multiple services

**Comment by kuanhulio** [comment]
@EsmailELBoBDev2 

If you could, I'd like you to take a look at my commit (https://github.com/HookedBehemoth/neuters/commit/db7862d96b14244113c24db66b9a13f201d3a423) here. I'm going through a process of hardening Dockerfile and `docker-compose` files based off of my repository here (https://github.com/kuanhulio/server_infrastructure) and I'd like your take on it

**Comment by EsmailELBoBDev2** [comment]
Hello @kuanhulio, I can confirm it works except a little problem.
Whenever I run it, it errors out with:
```sh
ERROR: In file './docker-compose.yml', volume must be a mapping, not a NoneType.
```
and when I comment out `volumes:` it runs fine.

**Comment by kuanhulio** [comment]
Thanks for the response @EsmailELBoBDev2,

Is this specifically `neuters` or from my repository?

**Comment by HookedBehemoth** [comment]
Interesting. I'm using podman and it didn't have issues with that.

**Comment by EsmailELBoBDev2** [comment]
@kuanhulio Glad you fixed it :tada: 
@HookedBehemoth  I use docker compose. You can test it.
