### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by julianfairfax** [HookedBehemoth/neuters#11]
Since Reuters doesn't have any RSS feeds, this would be nice

**Comment by HookedBehemoth** [comment]
Sure. Would you like to PR this? I've used https://lib.rs/crates/rss before.

**Comment by Vinfall** [comment]
Haven't used the crate you mentioned, but I think [Reuters route by RSSHub](https://github.com/DIYgod/RSSHub/tree/master/lib/v2/reuters) may help you sort it out, esp. https://github.com/DIYgod/RSSHub/blob/master/lib/v2/reuters/common.js.

**Comment by Tourma** [comment]
OpenRSS is a project that, among other sites, it generates it's own Reuters RSS feed.
[https://openrss.org/www.reuters.com](https://openrss.org/www.reuters.com)

Different use-case, I can see myself using Neuters more, but my dad uses RSS a lot.
