### ISSUE TITLE
Can only get homepage articles; browser extension does not work

### ISSUE THREAD

**Issue by hynow** [HookedBehemoth/neuters#12]
Hello, the browser extension does not seem to work.  I can see a small number of articles on neuters.de, but am unable to access any other Reuters articles.

**Comment by HookedBehemoth** [comment]
Could you provide some examples? There are a few paths that I known to not work.
> on the neuters frontpage there is this link that doesn't work https://neuters.de/world/pro-putin-operatives-germany-work-turn-berlin-against-ukraine-2023-01-03/
it's supposed to redirect to https://www.reuters.com/investigates/special-report/ukraine-crisis-germany-influencers but that doesn't load either https://neuters.de/investigates/special-report/ukraine-crisis-germany-influencers/

**Comment by HookedBehemoth** [comment]
I see. I've never updated the build on AMO.
I'll get to it tomorrow.

**Comment by HookedBehemoth** [comment]
The add-on has been updated on the AMO https://addons.mozilla.org/en-US/firefox/addon/reuters-redirect/

**Comment by Chirunos** [comment]
> Could you provide some examples? There are a few paths that I known to not work.
> 
> > on the neuters frontpage there is this link that doesn't work https://neuters.de/world/pro-putin-operatives-germany-work-turn-berlin-against-ukraine-2023-01-03/
> > it's supposed to redirect to https://www.reuters.com/investigates/special-report/ukraine-crisis-germany-influencers but that doesn't load either https://neuters.de/investigates/special-report/ukraine-crisis-germany-influencers/

Does this still apply? The second page (and other ones in similar format) still gives me a 404.

**Comment by HookedBehemoth** [comment]
https://github.com/HookedBehemoth/neuters/issues/15
