### ISSUE TITLE
some articles gives 404

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [HookedBehemoth/neuters#14]
Hi, 
I tried to load up https://www.reuters.com/article/idUSKBN2B20NU in neuters and it kept giving me 404 page http://neuters.esmailelbob.xyz/article/us-france-ovh-fire-idUSKBN2B20NU but when I try other articles like https://neuters.esmailelbob.xyz/business/media-telecom/netflix-set-slowest-revenue-growth-ad-plan-struggles-gain-traction-2023-01-17/ it works fine

**Comment by HookedBehemoth** [comment]
This is unfortunate. These articles used to redirect to their longer variants like: https://www.reuters.com/article/us-france-ovh-fire/millions-of-websites-offline-after-fire-at-french-cloud-services-firm-idUSKBN2B20NU

I'll look into supporting this.

**Comment by HookedBehemoth** [comment]
@EsmailELBoBDev2 give it a try

**Comment by EsmailELBoBDev2** [comment]
Did not work with me :/

**Comment by HookedBehemoth** [comment]
I deployed it to my site and it works there. https://neuters.de/article/idUSKBN2B20NU
Don't know what to tell you...

**Comment by EsmailELBoBDev2** [comment]
ooh, I forgot to re-build it :). it works now https://neuters.esmailelbob.xyz/article/idUSKBN2B20NU
