### ISSUE TITLE
Give this project a more appealing name

### ISSUE THREAD

**Issue by mendel5** [HookedBehemoth/neuters#2]
Hi @HookedBehemoth , I really like this project!

I think it's always a good idea to name things in a way that allows people to quickly and easily understand what they are dealing with.
In my opinion, the current name `supreme-waffle` does not really convey that this project is an alternative front-end to Reuters.com .

Maybe we can find a name for this project that is a little bit more relatable? I'm interested to hear your suggestions.

**Comment by HookedBehemoth** [comment]
I'm bad with names.
Tending towards Reuters-Proxy.

**Comment by HookedBehemoth** [comment]
Thinking about it again, "neuters" sounds good too and the word meaning kinda fits too.

**Comment by HookedBehemoth** [comment]
Rebranded it to neuters with a new domain name [neuters.de](https://neuters.de)
The old domain will stay up and the redirect add-on isn't updated yet.

**Comment by mendel5** [comment]
@HookedBehemoth : I'm sorry to say this but I think `neuters` is not a good name. The word `to neuter` in the English language means to castrate an animal or in other words to remove an animal's reproductive organ.

My suggestion is to go with the name `reutex`. You can register the domain `reutex.org` which I just checked and is still available.

Please give me a feedback what you think about this.

**Comment by mendel5** [comment]
Hi @HookedBehemoth , have you had a chance to look at my previous comment? I'm happy to discuss it with you.
