### ISSUE TITLE
Deserialize to Box<[...]> instead of Vec<...>

### ISSUE THREAD

**Issue by HookedBehemoth** [HookedBehemoth/neuters#24]
Check if it's feasable to deserialize to Box<[...]> instead of Vec. Codesize and speed might be a consideration too. Maybe set up tests to ensure the functionality is the same.

If you see this and want to help, go ahead and send suggestions or a pull request.

**Comment by xbdmHQ** [comment]
> Check if it's feasable to deserialize to Box<[...]> instead of Vec. Codesize and speed might be a consideration too. Maybe set up tests to ensure the functionality is the same.
> 
> If you see this and want to help, go ahead and send suggestions or a pull request.

Hmm, try a search engine that brings accurate results: https://search.whateveritworks.org/search?q=Deserialize+to+Box%3C%5B...%5D%3E+instead+of+Vec%3C...%3E 

I will look into this soon
