### ISSUE TITLE
500 - IO error: Failed to read JSON: missing field `url` at line 1 column 34566

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [HookedBehemoth/neuters#26]
Hello, 
I have problem with neuters and I use docker-compose version on debian, I use nginx reverse proxy and I tried to remove the `/` at end of `proxy_pass` but still did not work.
Thanks.

PS: I disable docker logs for extra privacy but if you need it, I can enable it to assist you.

**Comment by HookedBehemoth** [comment]
Does that also happen on neuters.de?

**Comment by EsmailELBoBDev2** [comment]
> Does that also happen on neuters.de?

Nope

**Comment by EsmailELBoBDev2** [comment]
Update: oh it works

**Comment by EsmailELBoBDev2** [comment]
Yes can confirm it too https://neuters.esmailelbob.xyz/

**Comment by EsmailELBoBDev2** [comment]
Hey @HookedBehemoth I wonder if there proxy setup or was it rate limiting?

**Comment by HookedBehemoth** [comment]
Please don't report issues with your instance if you aren't using my patches. I can now see that your instance has diverging commits.

**Comment by EsmailELBoBDev2** [comment]
I update my commit later, and what do you mean with "diverging commits"
