### ISSUE TITLE
404 on the 2nd page

### ISSUE THREAD

**Issue by newptcai** [HookedBehemoth/neuters#38]
When trying to read the 2nd page of articles: https://neuters.de/world/?steps=8&offset=8

you will get a 404 page.

**Comment by mescoba34** [comment]
Same issue here when clicking on 'next" arrow, to https://neuters.de/world/?steps=8&offset=8
Chromebook PC
Google Chrome Version 126.0.6478.178 (Official Build) (64-bit)

**Comment by HookedBehemoth** [comment]
If you find a reliable sitemap for all the categories, we could handle those properly. The last commit hardcoded world but there are many others. I've been reluctant on adding them because it was too arbitrary.

**Comment by mescoba34** [comment]
THANKS!  working!!
