### ISSUE TITLE
legality of neuters

### ISSUE THREAD

**Issue by gi-yt** [HookedBehemoth/neuters#9]
>  Republication or redistribution of Reuters content, including by framing or similar means, is prohibited without the prior written consent of Reuters. Reuters and the Reuters logo are registered trademarks, and trademarks of the Thomson Reuters group of companies.

is neuters affected by this?

**Comment by toyboatcash** [comment]
NO you should be fine, I don't see an issue as neuters proxy the request you're not storing the content on the neuters instance. Might be worth adding a disclaimer, those if you want to be on the safe side something like. 
Notice
All images and media are from Reuters. Neuters does not allow uploads or comments. Any issues with content should be reported to Reuters.
